version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - JWT_SECRET=senha_super_secreta
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend